server:
  port: 8000
#-----------------------------------------
spring:
  data:
    mongodb:
      database: instagram-media
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 5MB
      max-request-size: 20MB
#-----------------------------------------
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
#-----------------------------------------
file:
  upload-dir: /home/manhtv7/projects/instagram/image-store/
  path:
    prefix: /images

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey
