server:
  port: 8003

spring:
  data:
    neo4j:
      uri: bolt://localhost:7687
      username: neo4j
      password: 9092hnamnarT,

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              deserializer: org.apache.kafka.common.serialization.StringDeserializer
        bindings:
          instagramGraphChanged:
            consumer:
              startOffset: latest
              autoCommitOffset: false
      bindings:
        instagramGraphChanged:
          destination: instagram.graph.changed
          contentType: application/json
          group: graphService
          consumer:
            startOffset: latest
            autoCommitOffset: false

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

security:
  basic:
    enable: false

  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey