server:
  port: 8001
#-----------------------------------------
spring:
  data:
    mongodb:
      database: instagram-post
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            key:
              serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        instagramPostChanged:
          destination: instagram.post.changed
          contentType: application/json
#-----------------------------------------
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
#-----------------------------------------
security:
  basic:
    enable: false
  jwt:
    uri: /auth/**
    header: Authorization
    prefix: Bearer
    expiration: 86400
    secret: JwtSecretKey